### ISSUE TITLE
Publish the new iOS support

### ISSUE THREAD

**Issue by wmgandresg** [sonikro/flutter-okta-sdk#11]
Hey @Perdiga @sonikro 

I'm wondering when the new iOS support PR that was merged recently is going to be publish at pub.dev

Thanks!

**Comment by Perdiga** [comment]
> Hey @Perdiga @sonikro
> 
> I'm wondering when the new iOS support PR that was merged recently is going to be publish at pub.dev
> 
> Thanks!

working on it

**Comment by Perdiga** [comment]
@wmgandresg done. 

I am closing this issue as the version has been published
