### ISSUE TITLE
App crashes when cancel the login page

### ISSUE THREAD

**Issue by ghost** [sonikro/flutter-okta-sdk#30]
Hi:
After imported the package, I am able to see the okta login page, as the plugin (for example the login function) has no return value, so the app doesn't know if the page returns any error.
This causes our app to crash.
Do you have any plan to fix this? 
Or am I using it incorrectly? 
Thanks

**Comment by marktefftech** [comment]
Hi @RaymondFrogParking I'm sorry but I'm not understanding the issue, can you please provide some screenshots? Please make sure you follow the instructions outlined in the README

**Comment by ghost** [comment]
Hi @marktefftech Thanks for the reply, I followed the instructions in README, the Okta plugin is working fine in normal operations, but if the Okta login page shows up, instead of input login details, I click the Cancel or X button, the app crashes. 
The code sample in README:
if (oktaSdk.isInitialized == false) {
  await this.createConfig();
}
var result = await oktaSdk.signIn();

The above example shows there is a return value for oktaSdk.signIn() but after we installed the plugin Dev.7, the return type for signIn is void which returns nothing, so we cannot get the actual signIn result back from the sdk.
Please let me know if anything is unclear.
Thanks in advance.

**Comment by marktefftech** [comment]
@RaymondFrogParking Is this your own implementation of the SDK, or are you using the sample app? It sounds like a known issue occurring on iOS. If so take a look at this [podfile](https://github.com/marktefftech/flutter_okta_sample/blob/master/ios/Podfile) from an updated sample app

**Comment by ghost** [comment]
@marktefftech We are using the SDK and got the problem I described above, the issue is caused by Android and iOS handles the response differently, we currently have a hot fix directly to the sdk and import the sdk as a local package, but we prefer the fix can be done via the official channel. 
Thanks

**Comment by marktefftech** [comment]
@RaymondFrogParking Please note that this project is not officially supported by Okta but rather community-supported.

It would be helpful if you could raise the fix as a PR here as well please.

**Comment by marktefftech** [comment]
@RaymondFrogParking Please disregard above as I didn't see PR #31. Will review soon

**Comment by marktefftech** [comment]
Addressed in PR #31
