### ISSUE TITLE
Add support to iOS

### ISSUE THREAD

**Issue by Perdiga** [sonikro/flutter-okta-sdk#6]
Add the same operations available on Android to iOS

**Comment by nhancv** [comment]
any plan for iOS @Perdiga @sonikro ?

**Comment by sonikro** [comment]
@nhancv,  we don't have access to a Macbook machine right now, so we are searching for someone willing to contribute on our project.

**Comment by chaitanya-bhagavan** [comment]
@sonikro I have sent a PR for this. Could you please review and merge it.

**Comment by sonikro** [comment]
@chaitanya-bhagavan , great ! Thanks for contributing. I'll borrow my girlfriends's Macbook to test it out

**Comment by chaitanya-bhagavan** [comment]
@sonikro Did you get a chance to review the code ?

**Comment by sonikro** [comment]
Hello @chaitanya-bhagavan,. I'll approve the PR. Could you please update the README file to include the iOS part ? I'll also add you as a contributor to this project, so you can help us with the iOS part.

**Comment by chaitanya-bhagavan** [comment]
@sonikro I have updated the README. I have added a new property _issuer_ in BaseRequest.
